spring.datasource.url=jdbc:mysql://localhost:3306/bank_management?createDatabaseIfNotExist=true
spring.datasource.username=anand
spring.datasource.password=Anand@#1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true